// X6 (SPEC-exec-report §5.1) — the paste-ready Markdown manager report. PURE:
// a ManagerReport in → GitHub-flavoured Markdown out, byte-stable. The full
// fixture pins the exact layout a DS manager pastes into a monthly update.
import { describe, expect, it } from "vitest";
import {
	buildManagerReport,
	type ManagerReport,
} from "../../../src/engines/report/manager-report.js";
import { renderManagerMarkdown } from "../../../src/render/markdown/manager.js";

const FULL: ManagerReport = buildManagerReport({
	project: "acme",
	generatedAt: "2026-10-05T12:00:00.000Z",
	windowDays: 30,
	readinessThreshold: 80,
	systemScore: {
		current: 76,
		components: [],
		trend: [
			{ date: "2026-09-01", score: 70 },
			{ date: "2026-09-15", score: 73 },
			{ date: "2026-10-01", score: 76 },
		],
	},
	scoreVelocity: {
		delta: 6,
		windowDays: 30,
		direction: "up",
		regressionStreak: 0,
	},
	adoptionTrend: [
		{ date: "2026-09-01", pct: 79 },
		{ date: "2026-10-01", pct: 82 },
	],
	importCoverage: { imported: 12, total: 20, uncovered: [], uncoveredTotal: 8 },
	targets: [
		{ metric: "on-system", measured: 82, target: 80, op: ">=", band: "green" },
		{ metric: "parity", measured: 62, target: 80, op: ">=", band: "red" },
		{
			metric: "a11y",
			measured: undefined,
			target: 0,
			op: "==",
			band: "unknown",
		},
	],
	consistency: { score: 91, components: [] },
	debt: {
		pct: 18,
		level: "low",
		items: [
			{
				kind: "off-system",
				subject: "off-system values",
				count: 9,
				weight: 2,
				recommendation:
					"Tokenize 9 off-system values (run /ds-bridge:ds-lint --fix)",
			},
		],
	},
	dataFreshness: [
		{ kind: "lint", lastRun: "2026-10-05", ageDays: 0, band: "green" },
		{ kind: "drift", lastRun: "2026-09-20", ageDays: 15, band: "amber" },
		{ kind: "a11y", lastRun: "2026-08-01", ageDays: 65, band: "red" },
		{ kind: "impact", band: "unknown" },
	],
	frames: [
		{
			key: "f:1",
			frameName: "Checkout | step 1",
			latest: 85,
			runs: 4,
			passRate: 75,
		},
		{ key: "f:2", frameName: "Profile", latest: 60, runs: 2, passRate: 50 },
	],
});

const FULL_MD = `# Design system report: acme

Report date 2026-10-05 · changes over the last 30 days

| Metric | Now | Change |
| --- | --- | --- |
| System score | 76/100 | ▲ +6 in 30 days |
| On-system usage | 82% | +3 pts since 2026-09-01 |
| Component import coverage | 60% (12 of 20) | — |
| Consistency | 91/100 | — |
| Design debt | 18/100 (low) | — |
| Handoff readiness | 1 of 2 frames ready | — |

Score trend: ▁▅█ (3 runs)

## Targets

| Target | Now | Goal | Status |
| --- | --- | --- | --- |
| On-system usage | 82% | ≥ 80% | On track |
| Figma↔code parity | 62% | ≥ 80% | Off track |
| a11y | — | = 0 | Not measured |

## Top risks

1. Figma↔code parity is off target: 62% vs goal ≥ 80%
2. 1 of 2 tracked frames is below the 80 readiness bar (lowest: "Profile" at 60)
3. Stale data: a11y not measured recently

## Next actions

1. Bring Figma↔code parity to ≥ 80% (now 62%)
2. Tokenize 9 off-system values (run /ds-bridge:ds-lint --fix)
3. Raise handoff readiness of "Profile" from 60 to 80+ (run ds-bridge handoff)

## Handoff readiness by frame

| Frame | Readiness | Pass rate | Runs |
| --- | --- | --- | --- |
| Profile | 60 | 50% | 2 |
| Checkout \\| step 1 | 85 | 75% | 4 |

## Data coverage

- Measured: lint (today), token drift (15d ago)
- Stale: a11y (65d ago)
- Never measured: impact

_Design debt is a weighted index (deprecated ×8, detached ×5, off-system ×2 per item), capped at 100._

_Generated by ds-bridge (\`report --format exec\`) from \`.ds-bridge/history.jsonl\`. Numbers marked "not measured" were never recorded; they are not zero._
`;

describe("renderManagerMarkdown", () => {
	it("renders the full one-pager byte-for-byte", () => {
		expect(renderManagerMarkdown(FULL)).toBe(FULL_MD);
	});

	it("is deterministic", () => {
		expect(renderManagerMarkdown(FULL)).toBe(renderManagerMarkdown(FULL));
	});

	it("renders an empty report with not-measured rows and hints", () => {
		const md = renderManagerMarkdown(
			buildManagerReport({
				project: "fresh",
				generatedAt: "2026-10-05T12:00:00.000Z",
				windowDays: 30,
				readinessThreshold: 80,
			}),
		);
		expect(md).toContain("| System score | not measured | — |");
		expect(md).toContain("| Handoff readiness | not measured | — |");
		expect(md).not.toContain("Score trend:");
		expect(md).toContain("No targets set.");
		expect(md).toContain("No risks flagged.");
		expect(md).toContain("Nothing urgent.");
		expect(md).toContain("ds-bridge handoff <frame-url>");
		expect(md).toContain("- No checks recorded yet. Run `ds-bridge record`.");
	});

	it("labels a nameless frame by its key and pluralises a one-day window", () => {
		const md = renderManagerMarkdown(
			buildManagerReport({
				project: "p",
				generatedAt: "2026-10-05T00:00:00.000Z",
				windowDays: 1,
				readinessThreshold: 80,
				frames: [
					{ key: "name:", frameName: "", latest: 40, runs: 1, passRate: 0 },
				],
			}),
		);
		expect(md).toContain("changes over the last 1 day\n");
		expect(md).toContain("| name: | 40 | 0% | 1 |");
		expect(md).toContain('(lowest: "name:" at 40)');
		// No debt measured → no debt-index footnote.
		expect(md).not.toContain("weighted index");
	});

	it("shows a falling and a flat score with their arrows", () => {
		const down = renderManagerMarkdown(
			buildManagerReport({
				project: "p",
				generatedAt: "2026-10-05T00:00:00.000Z",
				windowDays: 14,
				readinessThreshold: 80,
				systemScore: { current: 60, components: [], trend: [] },
				scoreVelocity: {
					delta: -4,
					windowDays: 14,
					direction: "down",
					regressionStreak: 1,
				},
			}),
		);
		expect(down).toContain("| System score | 60/100 | ▼ −4 in 14 days |");
		const flat = renderManagerMarkdown(
			buildManagerReport({
				project: "p",
				generatedAt: "2026-10-05T00:00:00.000Z",
				windowDays: 14,
				readinessThreshold: 80,
				systemScore: { current: 60, components: [], trend: [] },
				scoreVelocity: {
					delta: 0,
					windowDays: 14,
					direction: "flat",
					regressionStreak: 0,
				},
			}),
		);
		expect(flat).toContain("| System score | 60/100 | no change in 14 days |");
	});
});
